/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzq_ndkdemo_ndk_Load */

#ifndef _Included_com_lzq_ndkdemo_ndk_Load
#define _Included_com_lzq_ndkdemo_ndk_Load
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzq_ndkdemo_ndk_Load
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lzq_ndkdemo_ndk_Load_addInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lzq_ndkdemo_ndk_Load
 * Method:    getNdk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lzq_ndkdemo_ndk_Load_getNdk
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
